# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bergenbutikker.no
email: kontaktoss@bergenbutikker.no
description: > # this means to ignore newlines until "baseurl:"
  Dette er en side for å finne lokasjonen til butikkene i bergensområdet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bergenbutikker.no" # the base hostname & protocol for your site
twitter_username: Bergenbutikker
github_username:  Bergenbutikker
headimg: "_includes/FramsideBiler2.jpg"

# Build settings
markdown: kramdown
